name: Release Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish_new_version:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: prepare yarn
        run: |
          corepack enable yarn
          yarn config set npmScopes.paosder.npmAuthToken ${{ secrets.NPM_PUBLISH_TOKEN }}
      - uses: actions/github-script@v3
        name: Modify package.json
        id: new-version
        with:
          script: |
            const fs = require('fs');
            const packageJson = JSON.parse(fs.readFileSync('package.json', { encoding: 'utf-8' }));
            packageJson.version = context.payload.ref.replace(/refs\/tags\/v/g, '');
            console.log(`new version: ${packageJson.version}`);
            fs.writeFileSync('package.json', JSON.stringify(packageJson, null, 2));
            return `v${packageJson.version}`;
      # - name: Check for modified files
      #   id: git-check
      #   run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)
      - name: Publish package to npm registry
        # if: steps.git-check.outputs.modified == 'true'
        run: yarn npm publish
